# Generated by Django 5.1 on 2024-08-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoFilmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameActor', models.CharField(max_length=200, verbose_name='Nome do ator')),
                ('birthday_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('nationality', models.CharField(choices=[('Estados Unidos', 'USA'), ('Brasil', 'Brazil')], max_length=100, verbose_name='Nacionalidade')),
            ],
            options={
                'verbose_name': 'Ator',
                'verbose_name_plural': 'Atores',
            },
        ),
        migrations.AlterModelOptions(
            name='generemodel',
            options={'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
    ]
