# Generated by Django 5.1 on 2024-08-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoFilmes', '0002_actormodel_alter_generemodel_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActorModel',
            new_name='Actor',
        ),
        migrations.RenameModel(
            old_name='GenereModel',
            new_name='Genre',
        ),
    ]
