# Generated by Django 5.1 on 2024-08-23 21:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoFilmes', '0003_rename_actormodel_actor_rename_generemodel_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('realese_data', models.DateField(blank=True, null=True, verbose_name='Data de lançamento')),
                ('actors', models.ManyToManyField(to='catalogoFilmes.actor', verbose_name='Atores')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre', to='catalogoFilmes.genre', verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'informe um valor entre 0 e %'), django.core.validators.MaxValueValidator(5, 'infome o valor entre 0 e 5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviws', to='catalogoFilmes.movie', verbose_name='Filme')),
            ],
        ),
    ]
