# Generated by Django 5.1 on 2024-08-23 22:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoFilmes', '0004_movie_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie', to='catalogoFilmes.genre', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'informe um valor entre 0 e 5'), django.core.validators.MaxValueValidator(5, 'infome o valor entre 0 e 5')]),
        ),
    ]
