# Generated by Django 5.1 on 2024-08-23 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoFilmes', '0006_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie', to='catalogoFilmes.genre', verbose_name='Gênero'),
        ),
    ]
