# Generated by Django 5.1 on 2024-08-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoFilmes', '0007_alter_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sinpse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
